### ISSUE TITLE
Analysis ready to be tested

### ISSUE THREAD

**Issue by Suor** [idrdex/star-django#11]
I created [basic UI](http://dev.stargeo.io/analysis/) to create and review analyses.

**Comment by Suor** [comment]
Summoning @dhimmel

**Comment by Suor** [comment]
Big analyses won't work on this instance - not sufficient memory - http://dev.stargeo.io/analysis/72/log/.
Multiple sclerosis failed cause there is an error in control query: single "=" instead of double.

I made exception show in log - http://dev.stargeo.io/analysis/72/log/.

**Comment by Suor** [comment]
I will upgrade instance tomorrow to bigger one.

**Comment by dhimmel** [comment]
Great. Will memory still be an issue on the bigger instance? If so maybe [dask](http://dask.pydata.org/en/latest/) is worth looking into.

**Comment by dhimmel** [comment]
> Multiple sclerosis failed cause there is an error in control query: single "=" instead of double.

Is there a way to delete or hide my malformed MS analysis?

Also it may make sense to have some sort of time-based versioning for analyses. Say I tag additional samples and want to rerun an existing analysis.

**Comment by Suor** [comment]
Updated an instance, it is now availabe on 54.187.239.77 address, you can add
```
54.187.239.77     dev.stargeo.io
```
line to your hosts file untill @idrdex updates domain DNS. This instance size should be sufficient for all analyses now.

I reran Parkinson's disease analysis. I will add some more controls, like deleting or rerunning analysis.

**Comment by idrdex** [comment]
I updated the domain DNS with godaddy.  http://dev.stargeo.io should work for now.

**Comment by Suor** [comment]
Added "Log", "Run a copy", "Rerun" and "Delete" buttons to analysis. Also is showing it's conditions and stats on its page.

**Comment by Suor** [comment]
Some bugs surfaced after trying to switch to using best available annotations - ones from series/sample_annotation tables and not from series/sample_tag. I'll fix it today.

**Comment by Suor** [comment]
Uploaded new code with fixes to analysis, nicer error messages there. 

Also switched analysis source to best available annotations (stored in `sample_annotation` and `series_annotation` tables) from initial ones (stored in `sample_tag` and `series_tag` tables).

**Comment by Suor** [comment]
Also, why are you deleting all the analyses you are running? Is it even intended or a bug?

**Comment by Suor** [comment]
Several updates:
- fixed Aging2 analysis, as well as ay other ones based on numeric data,
- newly created tags now corretly show up,
- fill in created_by/modified_by for new and updated tags and analyses.
