### ISSUE TITLE
Mapping ontologies

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#12]
We eventually need to move to ontologies that better describe tags vs the current free text.  Here is an example of js powered 'widgets' that we can incorporate when we define new tags: http://milportal.ncor.buffalo.edu/ontologies/10002?p=widgets

**Comment by dhimmel** [comment]
I was getting a connection error. I haven't ever seen a good ontology browswer of search engine. They mostly have bad UI/UX and are laggy. Interested to see what you come with. If need be, I can process most ontologies into table formats.

**Comment by idrdex** [comment]
The Graph Visualization Tree Hierarchy seem broken.  However, Form Autocomplete works well.  I particularly Example 3 (get the preferred name for a term).  More at http://www.bioontology.org/wiki/index.php/NCBO_Widgets.

**Comment by idrdex** [comment]
This stanford mirror works well: http://ncbo-stg-app-12.stanford.edu/ontologies/DOID?p=widgets

**Comment by zhilongjia** [comment]
It seems the disease ontology does not cover all kinds of diseases, though normalizing these terms will be convenient for analyzing. Currently, these free text tags are not friendly to users who are not created them.
ref: https://github.com/DiseaseOntology/HumanDiseaseOntology

**Comment by Suor** [comment]
This was implemented some time ago.

**Comment by idrdex** [comment]
Seems to not be working consistently.  See http://stargeo.org/tags/7/.  The correct ontology mapping is: DOID:12206 which doesn't come up in the inline search.

**Comment by idrdex** [comment]
As @Suor suggested, we should change to '2-level' ontology mapping to ensure that any concept can be directly assigned.

**Comment by ir4y** [comment]
There are some useful links.
http://bioportal.bioontology.org/ontologies/MESH?p=widgets
https://www.bioontology.org/wiki/index.php/NCBO_Widgets#Ontology_search_widget
http://bioportal.bioontology.org/search/

**Comment by ir4y** [comment]
@idrdex I have implemented new ontology and concept autocomplete widget.
This changes are deployed to the production server.

**Comment by idrdex** [comment]
@ir4y @Suor I think there is a bug in Concept widget in both Ontology and Concept match to the same thing.  Ontology works as expected.  However, should be Concept should be context-sensitive to the Ontology choice and map to the leaves of the chosen ontology.

**Comment by Suor** [comment]
Works as you described for me. Can you please make an explicit example? What you are typing where and in what sequence.

UI is somewhat broken though. A popup appears in strange place and without a bottom line.

**Comment by idrdex** [comment]
Sems to be working now.  Perhaps a Safari cache problem or something.
