### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#16]
http://dev.stargeo.io/analysis/83/log/

**Comment by Suor** [comment]
I returned to older (not broken) analysis code and reran this - http://dev.stargeo.io/analysis/121/. Looks like there is other error involved. 

#15 and #14 also appear to be caused by same error after rerun.

**Comment by Suor** [comment]
After updating code it became clear that this was caused by insufficient data. You can't make a meta-analysis of on source. I added a check to show nice FAIL message: http://dev.stargeo.io/analysis/121/log/

**Comment by dhimmel** [comment]
> FAIL Can't perform meta-analysis on single source

Is this a limitation of the meta-analysis method? Intuitively, you should still be able to get an effect size and p-value for each gene. For my project where some diseases may only have a single study, support for n = 1 would be appreciated.

**Comment by Suor** [comment]
The definition of meta-analysis is a way to combine several studies, so we probably can't transparently allow this. In a case of each analysis, however, an analysis for each source is performed, this is named fold change analysis in the code. You can probably use that, there is no UI for that though.

@idrdex could probably add to this.
