### ISSUE TITLE
Implement independant login

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#18]
We should shut down the old site once analysis is relatively stable.

**Comment by Suor** [comment]
So this is done.

A few clarifications and consequences:
- old website still works, but will break as users are added.
- all passwords are lost, to login everyone should follow "Lost password?" link on [login form](http://dev.stargeo.io/accounts/login/).
- users can't register (for now), but could be added by superuser (currently Dexter and me) in [admin](http://dev.stargeo.io/admin/). Log into admin with the same credentials you use on website (once you restored your password), go to Users -> Add User and create one there. Fill email into username fields everythere. After user creation you can fill his/her first and last names as well as email in a separate step.
- I disabled database migration on old website and this shouldn't be enabled or db schema will be broken with possible data loss. Also, **if you use local working copy of the old app connecting to real db, then disable migration there as well**. This could be done with `DAL(..., migrate_enabled=False, ...) ` in `models/db.py`.

**Comment by idrdex** [comment]
We need to accept new users.
