### ISSUE TITLE
Automated analyses

### ISSUE THREAD

**Issue by dhimmel** [idrdex/star-django#22]
I have prepared [67 queries](https://github.com/dhimmel/stargeo/blob/01f40e12ed2a2844113e0b2ce8f0afb1e6fd8a2c/data/queries.tsv). Manually entering each analysis would be time consuming and error prone. Is there a way to automatically run these queries?

Before proceeding, I should check that the listed tags actually still exist in the database. @idrdex or @Suor can you privately send me database credentials? Read only access is sufficient. Then I can use my [existing method](https://github.com/dhimmel/stargeo/blob/01f40e12ed2a2844113e0b2ce8f0afb1e6fd8a2c/retrieve-tags.ipynb) to programatically retrieve all tags.

Finally, for each executed analysis it would be nice to store the reproducibility information discussed in #20. For example, which series were included and which samples were cases and controls. If these features are still in development, perhaps I could just make the relevant database queries right before submitting the analysis.

**Comment by idrdex** [comment]
@dhimmel for now I put us local analysis code you can use here: https://github.com/idrdex/star_api/blob/master/analysis.py

**Comment by dhimmel** [comment]
@idrdex, I made some [changes to your code](https://github.com/dhimmel/stargeo/commit/153688869fb87412dd716ac27994e51baeb16078#diff-4909080c30c60e66ea2bc737dec49287), to make `analysis.py` more modular. My goal is to call analyses from a [separate notebook](https://github.com/dhimmel/stargeo/blob/153688869fb87412dd716ac27994e51baeb16078/analysis.ipynb). See the notebook for the error I'm getting when I run analyses. This happens when running your Dengue analysis in `analysis.__main__` as well.

Any advice?

**Comment by Suor** [comment]
It's now possible to automatically start analysis on stargeo via API:
```python
import requests

auth_headers = {'Authorization': 'Token your-token-here'}
r = requests.post('http://localhost:5000/api/v2/analysis/', headers=auth_headers, data={
    'analysis_name': 'Psoriasis',
    'specie': 'human',
    'case_query': "psoriasis=='psoriasis'",
    'control_query': "psoriasis_control=='psoriasis_control'",
})
r.json()
# {'created': 383}
```
You can get your auth token on [this page](http://stargeo.org/docs/) (you need to be logged in). You can pass parameters: analysis_name, description, specie, case_query, control_query, modifier_query and min_samples. You can fetch analysis results once its done via:
```python
r = requests.get('http://stargeo.org/api/v2/analysis/383/results/')
assert r.ok
df = pd.io.json.read_json(r.text, orient='split')
```
