### ISSUE TITLE
Possible to get analysis working for one study only?

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#24]

**Comment by Suor** [comment]
You can select by series_id. E.g. add something like `series_id==123` to modifier.

**Comment by panjames** [comment]
I tried series_id==GSE43452 and it gave me 

UndefinedVariableError: name 'gse43452' is not defined

http://dev.stargeo.io/analysis/225/log/

**Comment by Suor** [comment]
`series_id` is not the same as `gse_name`.  You can't select by that currently cause `gse_name` is not in analysis dataframe. I can add it there if it's needed. 

By the way `series_id` for GSE43452 is 8281. You can see it in address here - http://dev.stargeo.io/annotate/?series_id=8281.

**Comment by panjames** [comment]
I tried series_id==8281 but it's still giving me "can't perform on single source"

http://dev.stargeo.io/analysis/231/log/

**Comment by Suor** [comment]
Because you can't make meta-analysis on single source. On implementation level is that our math will end with zero division anyway. On definition level is that meta-analysis = joining several analyses, more than one. It's unclear what you are trying to do.

BTW it would work if serie had several analyses, e.g. with different platforms.

**Comment by dhimmel** [comment]
## Analyzing a single case control analysis

I think it would be nice to support analyses with only a single series. I don't see why the fixed effects meta-analysis would fail -- the results would just be that of a single two-sampled equality of means test.

Analyzing a single study would be helpful to users, and helpful for my project where I may want disease signatures even if there is only 1 tagged study.

**Comment by idrdex** [comment]
Agreed. But this site only does meta analysis analyses. And n=1 just does not make sense. However don't despair. Check out: https://github.com/idrdex/star_api. It gives you sample level access to the series matrix files and some convenience methods for combining cross platform for machine learning.
