### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#25]
http://dev.stargeo.io/analysis/221/log/

**Comment by panjames** [comment]
This error keeps popping up in every analysis I do. Here's another one: http://dev.stargeo.io/analysis/227/log/

@idrdex -- seems to be breaking everything, no?

**Comment by Suor** [comment]
It was an error in logging, I fixed that and reran analysis. Unforturnately it was just masking actual error in analysis. I will take a look at it now.

**Comment by Suor** [comment]
Closing as dulicate #27
