### ISSUE TITLE
Add min samples paramater to analysis

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#28]
We need to add a paramater to the analysis input for minimum number of samples (per label ie min cases or min controls). The default should be 3. This is an important QC measure.

**Comment by dhimmel** [comment]
I see a lot of studies that pooled samples, so effectively there is 1 case and 1 control. I assume this strategy is a cost saving technique. Are all of these pooled studies effectively useless because you can't calculate per-gene measurements of variation?

**Comment by idrdex** [comment]
I suspect for meta analysis yes. But the API gonna do cross platform integration and normalization so maybe it's useful. U wanna meet next week? Grant due Monday but free after. 

dex*

**Comment by dhimmel** [comment]
> cross platform integration and normalization

Sounds advanced + powerful

> U wanna meet next week? Grant due Monday but free after.

Yes, will email.

**Comment by Suor** [comment]
Implemented this.
