### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#29]
The email never comes...

**Comment by Suor** [comment]
Look into spam folder, if it's not there then please tell me your email.

**Comment by Suor** [comment]
Did it help?

**Comment by dhimmel** [comment]
I was able to reset my password.

**Comment by idrdex** [comment]
@panjames is this working for you?

**Comment by panjames** [comment]
Didn't get anything. @Suor - my email is japan@stanford.edu

**Comment by Suor** [comment]
@panjames did you tried resetting once more? Did you check spam folder?

**Comment by Suor** [comment]
Also, do you see this message when resetting password?

> We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

> If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.

**Comment by panjames** [comment]
Just tried it again. Still nothing. Also checked spam folder.

**Comment by Suor** [comment]
Looked up, no errors, so email is sent, but silently dropped somewhere, e.g. by your email provider. You can contact him, I will be surprised if this helps though. Alternatively I can manually change your email address to something else (preferrably something know to work like gmail).

**Comment by panjames** [comment]
Yeah, if you can change it to james.pan1@gmail.com that'd be great.

**Comment by idrdex** [comment]
How do I add new users?

dex*

**Comment by Suor** [comment]
@panjames updated.

**Comment by Suor** [comment]
@idrdex 

Log into [admin](http://dev.stargeo.io/admin/) with the same credentials you use on website (once you restored your password), go to Users -> Add User and create one there. Fill email into username fields everythere. After user creation you can fill his/her first and last names as well as email in a separate step.

**Comment by Suor** [comment]
This should be fixed now.
