### ISSUE TITLE
Abstracts in validation view

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#3]
When validating, it would be nice to be able to read the study abstract. Some studies are impossible to tag without deduction based on the the abstract.

**Comment by Suor** [comment]
Does this include blind validation? Won't it demask the serie? 
Also what field do you mean by abstract? `series_summary`?

**Comment by idrdex** [comment]
See: http://dev.stargeo.io/annotate/?series_id=1

Abstract is the series level information that you toggle in the Tag view with the "More" handle.  We should have that for the validation view too.  Both blind and on - demand.  It may damask the blind validations, but thats ok.  Most of the descriptions don't have any identifier (like GSE or GSM), and we want people to validate more than less.

**Comment by Suor** [comment]
Done.

Also, note that you can expand/contract annotation by clicking anywhere within it, no need to stretch to More/Less link.

**Comment by dhimmel** [comment]
> you can expand/contract annotation by clicking anywhere within it

I like this feature for expanding the abstract. However, once expanded it makes selecting text problematic because selecting text triggers the contraction. Is expand-only an option?

**Comment by Suor** [comment]
Ok, changed that behaviour.

2015-08-04 10:17 GMT+07:00 Daniel Himmelstein <notifications@github.com>:
