### ISSUE TITLE
Versions of pandas and numpy

### ISSUE THREAD

**Issue by zhilongjia** [idrdex/star-django#31]
Is the versions (in file requirements.txt) of pandas and numpy correct to make a working copy?

During the process of `./manage.py migrate` after sucessfully implement the first 3 steps (Keeping the .env file unchange), it results in 

     File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:23654)
    ValueError: numpy.dtype has the wrong size, try recompiling

I deleted the two package and installed numpy-1.10.1 pandas-0.17.0.

When I rerun `./manage.py migrate`

```
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "cannot import name get_standard_processors
```

I do not use python for a long time and know nothing about django so far.
Thank you.

**Comment by Suor** [comment]
I use numpy and pandas versions from `requirements.txt`. It's impossible to understand why it doesn't work for you without complete stacktrace. In the end these versions shouldn't really matter.

As for `debug_toolbar` error - I forgot to add it to requirements. You may install it with:
```shell
pip install django-debug-toolbar==1.3.2
```
