### ISSUE TITLE
Analysis Input

### ISSUE THREAD

**Issue by zhilongjia** [idrdex/star-django#32]
Here are some enhancements. I will show using psoriasis as an exmaple in some cases.
1. Showing example at the input frames will make it easy to use for users.
2. What is the "Description" used for?
3. Case query and Control query. The input of psoriasis=='psoriasis' and psoriasis_control=='psoriasis_control' can be psoriasis and psoriasis_control. (easy to use)
4. It seems every one can delete the analysis results even created by others. (did not try)
5. The table shows almost 2211 pages, which is too much. Can we just show the top 250 ranked by random_pval or else, while exporting will save all of them, like GEO2R?  Keeping sym (gene symbol) always showing even scroll left to check other columns in the table.

**Comment by Suor** [comment]
1. What do you mean by "example at the input frames"?
2. Description is for you, just a text note.
3. Adding special syntax will prevent passing it to `DataFrame.query()` and thus complicate implementation and limit functionality.
4. Yes, true.
5. Table shows everything, you can sort how you like. Everybody decides what is meaningful for himself.

**Comment by zhilongjia** [comment]
1.  As a user for the first time, I donot know the correct way to input it. (I input "psoriasis" and "psoriasis_control" respectively). Adding suggesting text to the input frame of Case query and Control query (see figure below) will make the user know what to input.
![lincs](https://cloud.githubusercontent.com/assets/1230436/11144297/85aa839c-89f3-11e5-940c-2d38dd459c59.png)
2. It seems it does not appear in the final results.
3. This is awkward for user to use from the view of user experience.
5. Showing so many is resource-consuming for the server and useless for the end user. BTW, we really need a detailed document for users, who want a clear explanation about their analysis results.

**Comment by Suor** [comment]
2. You can see it [here](http://dev.stargeo.io/analysis/254/) for example. It doesn't affect results.
4->5? Showing only part will be confusing and sometimes limiting. Server is ok for now, thinking on optimizing things before you need is a bad practice. Ultimately we will need some docs I agree.

**Comment by zhilongjia** [comment]
About 1 and 5, you're right. (github ordered them by itself, showing 4, even it's 5.)

**Comment by Suor** [comment]
No actionable suggestions, so closing for now. Someone may reopen with new ideas.
