### ISSUE TITLE
regex .* doesnot work

### ISSUE THREAD

**Issue by zhilongjia** [idrdex/star-django#33]
The ​*regex*​ used in the annotation does not work fully? To annotate GSE42296,  I need match two parts:  ​*non-responder*​ and ​*Rheumatoid arthritis*​, but ​__non-responder.*Rheumatoid arthritis__ does not work.  But I successfully tested it in [pythex](http://pythex.org/?regex=non-responder.*Rheumatoid%20arthritis&test_string=cell%20type%3A%20PBMC%7C%20%7Csubject%3A%20Patient%209%7C%20%7Cresponse%3A%20NR%20-%20non-responder%7C%20%7Ctreatment%3A%20Before%20treatment%7C%20%7Ctime%3A%20week%200%7C%20%7Cdisease%20state%3A%20Rheumatoid%20arthritis%0Acell%20type%3A%20PBMC%7C%20%7Csubject%3A%20Patient%204%7C%20%7Cresponse%3A%20NR%20-%20non-responder%7C%20%7Ctreatment%3A%20infliximab%7C%20%7Ctime%3A%20week%202%7C%20%7Cdisease%20state%3A%20Crohn%27s%20disease&ignorecase=0&multiline=1&dotall=0&verbose=0) .

I found it's due to there is space in the context (`cell type: PBMC| |subject: Patient 1| |response: R - responder| |treatment: Before treatment| |time: week 0| |disease state: Crohn's disease`).

It is probably related with smart DataTables in JS.

**Comment by Suor** [comment]
By default `.` doesn't match newlines. When tested you probably copy-pasted text which converted newlines to spaces.

I can switch regular expressions mode so that dot will match anything.

**Comment by Suor** [comment]
As discussed in #39 using `.*` is a bad idea, this can also be very slow when matching against long strings.
