### ISSUE TITLE
delete and merge tag

### ISSUE THREAD

**Issue by zhilongjia** [idrdex/star-django#34]
A way to delete and merge tags. 1. Deleting tags are useful if a wrong tag created. 2. Merging tags is for the same context but tagged differently. Thank you.

**Comment by Suor** [comment]
Implemented this. Only staff users can delete and merge tags, staff status can be granted in [admin](http://dev.stargeo.io/admin/auth/user/).

To delete tag click it and the click red "Delete" button to the right. To merge tag change its name to one of target tag.

**Comment by idrdex** [comment]
We need a way to delete original annotations. In fact the idea of annotation vs validation are relatively arbitrary given we have canonical annotations now. Moderators should be able to delete any annotation irrespective of the order (i.e. Including the original annotation). This feature may be a good reason to refactor the backend to remove the duplicate tables of annotation vs validation.

**Comment by Suor** [comment]
I was thinking about this for a while. But why are you reopening unrelated issue?

**Comment by Suor** [comment]
Even if it was related - the idea of issues is to make one for the issue even when it's an enhancment of an old one. This was they could be referencable in conversations, code and git messages.

**Comment by Suor** [comment]
Moved this to #68.
