### ISSUE TITLE
Rename tag not working properly

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#35]
nonsmoker tag was renamed to smoker_control, but some values remained as nonsmoker.

**Comment by zhilongjia** [comment]
I changed it and want deal with it automatically, but finally I did not use this tag as it's very general phenotype like age in stargeo. BTW, we probably can use [DiseaseOntology](https://github.com/DiseaseOntology/HumanDiseaseOntology) to normalising most of these tags. Currently, a short name is used for tag name. In some cases, it's not a standard way.

**Comment by idrdex** [comment]
Also a problem with hiv_healthycontrol.  It was apparently changed to hiv_control.  We need to find all these and assign the right values

**Comment by Suor** [comment]
Fixed renaming: everything now remaps correctly. Also fixed `Smoker_control` and `HIV_control`.

Also added some stats on [tag page](http://dev.stargeo.io/tags/170/), so that such errors will be obviously visible.
