### ISSUE TITLE
Make API to read basic things

### ISSUE THREAD

**Issue by Suor** [idrdex/star-django#36]
Mostly to enable local analysis without database access as now. Next steps would be updating `starapi` to use that and implementing write access to solve #22.

**Comment by idrdex** [comment]
@Suor we should probably revisit this in time for Dec 7th is possible.

**Comment by ir4y** [comment]
@Suor I have created a basic set of API endpoints.
Could you review it?

**Comment by Suor** [comment]
There should be an endpoint to get analysis df - like [this function](https://github.com/idrdex/star-django/blob/158851b14af74ac20e303f1346bb58005919dfb2/analysis/analysis.py#L140). The params are case_query, control_query, modifier_query and specie. modifier_query is optional. DF packed to json like S3Field does.

Also an API endpoint for [get_probes](https://github.com/idrdex/star-django/blob/158851b14af74ac20e303f1346bb58005919dfb2/analysis/analysis.py#L270). The result is dataframe with probe, mygene_sym and mygene_entrez columns.

**Comment by idrdex** [comment]
@Suor @ir4y lets talk about this tonight?

**Comment by Suor** [comment]
I am a bit tight on time today. Can we start a bit earlier like 10pm PST?

**Comment by ir4y** [comment]
@Suor 
I have added get_analysis_df endpoint. Could you review it ?
Is it implemented correct?

**Comment by ir4y** [comment]
@Suor I have changed API as you advised at our Friday call. I think it is very close being released.
Could you review it?  Or we can have another call about API on Monday.

**Comment by idrdex** [comment]
Sure. Let's Skype tonight?

dex* by iPhone

**Comment by Suor** [comment]
@idrdex it is purely technical review.

**Comment by Suor** [comment]
@ir4y sent review by email, next time make a pull request

**Comment by ir4y** [comment]
I have pushed API to the production.
@idrdex http://stargeo.org/docs/

**Comment by idrdex** [comment]
This looks great!  We need to expose the raw samples too.  This query will work:
`select sample.*, gpl_name, gse_name from sample
INNER JOIN platform on sample.platform_id = platform.id
INNER JOIN series ON sample.series_id = series.id;`

**Comment by ir4y** [comment]
@idrdex It's done http://stargeo.org/api/samples/

But there are 1 146 799 samples. It is a huge amount of data. How will users use this endpoint? Maybe we need to add a kind of search/filter for samples?

But if the common scenario will be downloading all samples I will refactor this code to serve samples as a static file which will be updated by the cron job.

**Comment by idrdex** [comment]
AGREED. Index/search by series id for sure. That is how people will make annotations through API. 

dex* by iPhone

**Comment by ir4y** [comment]
@idrdex I have added filtering by series and platform.

http://stargeo.org/api/samples/?series=GSE4579
http://stargeo.org/api/samples/?platform=GPL3348
http://stargeo.org/api/samples/?series=GSE4579&platform=GPL3348

**Comment by idrdex** [comment]
Thx @ir4y. Reopening because we also need to and enpoints to filter sample_annotations by tag_id, series, and platform.

**Comment by ir4y** [comment]
@idrdex 
Can it wait until 16 of May?

**Comment by idrdex** [comment]
Sure. Thx.

**Comment by idrdex** [comment]
Lets readdress this.  Now we have API posting, we also need updating as well.  So most importantly, 1) POST updates for series, 2) filter by tag_id.

**Comment by Suor** [comment]
> POST updates for series

What do you want to update in series? We grab them, any update will be overwritten anyway.

**Comment by ir4y** [comment]
@idrdex 
If you are talking about updating SeriesTag it doesn't make sense.
The ideology of stargeo is against any update as Alexander said.

There are two exceptions
* source data is too big, so we have to update them
* superuser can mark validation as deleted.

**Comment by Suor** [comment]
Reorganized API to follow Stargeo logic better plus some improvements:
- samples grouped in series, results in analysis, probes in platforms, sample annotations in series annotations,
- an endpoint to start new analysis,
- [docs](http://stargeo.org/api_docs/) with examples.

New API is available via `/api/v2/` url, old api is still available too, via old url. 

@idrdex if you want anything added start a new issue or reopen this. If you want to update docs you can edit [this ipython notebook](https://github.com/idrdex/star-django/blob/master/stuff/api.ipynb) and tell me regenerate the page.

**Comment by idrdex** [comment]
We need this to point to http://stargeo.org/docs/ like it did originally. Fine to have it redirect to http://stargeo.org/api_docs/, but the original publication points to http://stargeo.org/docs/.  See https://www.nature.com/articles/sdata2017125 @Suor @ir4y.

**Comment by Suor** [comment]
Added a redirect.
