### ISSUE TITLE
URGENT: Incorrect annotations saved instead of correct annotations

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#38]
I tried to ignore the incorrect annotations by clicking on the (X) button next to the annotator's name but it's not doing anything.

<img width="1103" alt="screen shot 2016-03-09 at 3 53 25 pm" src="https://cloud.githubusercontent.com/assets/5126677/13658277/66262bc8-e62a-11e5-8f5e-5858b5517d56.png">

**Comment by Suor** [comment]
Website correctly stops you from ignoring annotation because you are non-staff, showing crosses to you was an error.

Contact Dexter to give you staff status, this will allow you to ignore annotations and also delete and merge tags.
