### ISSUE TITLE
Dataset: GSE22226 regex no working for searching for pgr  

### ISSUE THREAD

**Issue by jspatz83** [idrdex/star-django#39]
Dexter and I have tried to use regex to tag GSE22226 dataset for pgr using the syntax

 pgr (0=negative; 1=positive;): 1

but regex search does not find the pgr in sample characteristic column. this regex syntax works for other items in this dataset, e.g. er (0=negative; 1=positive;): 1 but not for pgr. Dexter told me to log a issue on this forum to have it investigated.

**Comment by zhilongjia** [comment]
using `pgr.*\: 0` and `pgr.*\: 1`. `.*` means anything. Related with #33 .

**Comment by Suor** [comment]
Some things with regexes:

1. Some symbols are special, they don't much literally. E.g. `.` (dot) matches any single symbol, `(` and `)` are used to capture part of the match, they are mere instructions and don't match any symbols. To match special symbols you need to escape them in regex by prefixing with `\`, e.g. `\(` matches left parentheses.

2. Sometimes when you see a space in a text it's really several spaces or a newline or both mixed. Literal space will only match single space. To reliably match several spaces use ` +` (space then plus), to reliably match any sequence of whitespace characters use `\s+`.

3. `pgr.*\: 0` is really bad idea, which also won't work. Consider a line:
```
pgr (0=negative; 1=positive;): 1| |her2 (0=negative; 1=positive;): 0
```
The regex will match `pgr` then skip almost to the end and match `: 0`. And you probably didn't want to match this line. So this could appear to work while not really doing that. There are some ways to go about that:
```perl
# match literally with proper escapes and space quantifiers
pgr +\(0=negative; +1=positive;\): +0
# match as much non-colon as posible then collon and the rest
pgr[^:]+: +0
```
The first variant is very reliable (once you type it correctly:), but second one will work too.

**Comment by zhilongjia** [comment]
`pgr +\(0=negative; +1=positive;\): +0` will be a better one, though `pgr.*\: 0` works for me. Thank you @Suor

**Comment by Suor** [comment]
@zhilongjia this works now only through coincedence. The reason is there is a newline between `|`s and `.` doesn't match newline. If things change, e.g. there would be now newline after data update this will break.
