### ISSUE TITLE
We need a species interface

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#44]
We need to be able to incorporate more than just human data now.  For instance mouse would be the next big one.  Ideally we should work across all species.

**Comment by Suor** [comment]
Mouse and rat series and samples data is on stargeo and updated regulary. Probes are loaded now.

**Comment by idrdex** [comment]
Thx. @Suor.  We need some UI that restricts the species to human or mouse or whatever.  Human, mouse and rat are clearly the most important species, but ultimately we should have all of them accessible.

**Comment by Suor** [comment]
Add a filter to search and to analysis. For now it's human, mouse and rat. New species are to be added manually anyway.
