### ISSUE TITLE
ucsf emails not working for logon

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#49]
Not sure why mail server ucsf sent to @ucsf.edu domains.  Neither for new registration nor forgot password emails.  I think delivery to @gmail.com works fine.  We need to investigate this.

**Comment by Suor** [comment]
Should be fixed now.

**Comment by idrdex** [comment]
Reset dexter.hadley@ucsf.edu: said 'Unknown email dexter.hadley@ucsf.edu'.  Yet when I set up a new account with dexter.hadley@ucsf.edu, it said 'Email is aready in use.'

**Comment by Suor** [comment]
This is a misleading error message, and some limitations - like you can't reset an account if it's inactive and you can't resend an activation email.

Applied following changes and enhancements to fix this:
- you can now reset your password even if your account is inactive (you still can't log in),
- when your account is inactive and you try to login you get a message about that and a link to a form resending activation email (you can just go to your email and use old activation email, this is to combat missing mails)

An 'dexter.hadley@ucsf.edu' account is now inactive, this means you need to follow a link in activation email. If you don't have one you can resend it from here - http://stargeo.org/accounts/reactivate/.

**Comment by idrdex** [comment]
It works as  @ucsf.edu users can still log on.  For @gmail.com users activation works just fine.  Here's the @ucsf.edu error message:

![pasted1](https://cloud.githubusercontent.com/assets/1265923/20987266/d16bf066-bc80-11e6-85db-63ff7847e12c.png)

**Comment by idrdex** [comment]
It works as  @ucsf.edu users can still log on.  For @gmail.com users activation works just fine.  Here's the @ucsf.edu error message:

![untitled](https://cloud.githubusercontent.com/assets/1265923/20987402/5341ba08-bc81-11e6-92ce-88e826cd158f.png)

**Comment by Suor** [comment]
Have you tried resending activation email?

**Comment by Suor** [comment]
The thing is if you receive activation email then the link should work unless it's expired, it doesn't depend on mail provider.

The bigger issue is that login/register/activate thing is a pain anyway. The best solution people have come up with so far is social login like via Google, Facebook, Twitter, Github and so on. We can implement that if you want, would ease things quite a bit for newcomers. The only downside I see is that someone could end up with multiple accounts without even knowing (if he uses different emails on different services) and be very confused. Most people would however always use same gateway (like always Twitter) and be happy.

**Comment by Suor** [comment]
Closing since most possibly this was a result of an old link. Reopen if new links fail to work.
