### ISSUE TITLE
Some GSE from GEO are not availabe

### ISSUE THREAD

**Issue by hzc363** [idrdex/star-django#50]
I tried to search for a couple of GSE accession # (GSE2436, GSE90531, GSE77323, GSE64092) None of these GSE are on stargeo yet. All these GSE I tried to search for are mouse data. Please add the mouse data to the website.  

I realize that download the whole collection of mouse data from GEO may be a daunting task. So I made a list of GSE that I need the crowd to annotate. At least make GSEs on the list available on stargeo. The list can be found through this link:
https://ucsf.box.com/s/q0v8vpgfyfvmvhxxtuo5plskghb82j9d

**Comment by Suor** [comment]
All human, mouse and rat series should be already in. They are updated weekly so can not appear immediately on stargeo. There are some limitations on what is fetched:
- serie type should be "Expression profiling by array"
- there should be single and same specie for samples and platform

I started data refresh manually now and it already fetched GSE2436. I'll look why others are not fetched if they in fact aren't.

**Comment by Suor** [comment]
Refresh finished. GSE90531, GSE77323, GSE64092 have a type of "Expression profiling by high throughput sequencing" and thus skipped. Anything satisfying conditions should be in.

**Comment by Suor** [comment]
You can discuss those conditions with Dexter and reopen this issue if you'll decide to weaken them.
