### ISSUE TITLE
Competence test ground truth

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#51]
Bug in competence test of GSE42952 for age. Original annotation is wrong and subsequent validations are right. Competence test ground truth seems to be pegged to original annotation vs the actual annotation call.

**Comment by Suor** [comment]
This is not what's happening [as far as I can see](http://stargeo.org/annotations/1341/samples/). First column is our best effort derived annotation and it's not the same as original one.

**Comment by Suor** [comment]
Also checked competence test, looks like derived annotation not original is used. If you manage to reproduce please reopen this.

**Comment by idrdex** [comment]
@Barayikanti still has this issue.

**Comment by barayikanti** [comment]
So I'm still having this issue. For the past several weeks I've tried to pass the competence ground test, I get to the last series 5/5, but I keep getting it wrong, cause the tag is always associated with "age." Anyway to address this or bypass it?

**Comment by idrdex** [comment]
It really was a competence issue.
