### ISSUE TITLE
Summary results from search

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#54]
Search currently summarizes only the total number of studies (i.e. GSEs) found.  We also need to summarize on the same line the corresponding total number of samples (i.e. GSMs), platforms (i.e. GPLs) and species found.  For instance how many GSMs match 'cancer'?

**Comment by idrdex** [comment]
Let's just sum samples for efficiency in summary. That's what people really care about.

**Comment by ir4y** [comment]
This task is done and deployed.

You can see a total number of samples, platforms, and species found in the right part of the search table header.
