### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#56]
Lets post to the bottom of home page:

Research reported in this publication was supported by the National Cancer Institute of the National Institutes of Health under Award Number UH2CA203792. The content is solely the responsibility of the authors and does not necessarily represent the official views of the National Institutes of Health.

**Comment by idrdex** [comment]
Lets add a data license to this disclaimer.  I picked this one for now:

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">The Search Tag Analyze Resource for the Gene Expression Omnibus (STARGEO)</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="stargeo.org" property="cc:attributionName" rel="cc:attributionURL">Dexter Hadley</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by ir4y** [comment]
This is done.

**Comment by idrdex** [comment]
Need both disclaimers in this footer. About NIH funding. And data license.

**Comment by ir4y** [comment]
I have restored information about NIH funding.
