### ISSUE TITLE
On demand validation

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#6]
Oftentimes I want to see the tags already applied to a specific dataset. Sometimes I may want to validate or modify those tags. Othertimes, I make a mistake and want an easy way to modify my tag.

@idrdex and I discussed a potential mechanism where by clicking on a tag label, a dataset can be retagged/validated. Thoughts?

**Comment by idrdex** [comment]
Yeah. I think an on demand validation is a good idea. We could give the user as inter rater score (kappa relative to a consensus) when they are done the validation.

**Comment by Suor** [comment]
I implemented on demand validation, to start that search for a serie, click "Tag", then click any existing tag. This is not counted towards blind validations and won't stop them. However, any later agreeing with this blind validation will stop the process.

**Comment by dhimmel** [comment]
Okay, nice. It may be nice to have two colors of tag background colors.

One color indicates the series has been tagged by a user that is not you.
A second color indicates that you were the tagger.

This way for diseases that you really care about, you can make sure you have assessed every study.

**Comment by idrdex** [comment]
That would be a nice interface touch. Ultimately we won't pay for on demand validations. But we might use them to make final 'calls' on annotations. 

dex*

**Comment by Suor** [comment]
If serie has more than 1 platform when you can be the author of one annotation and not second.

**Comment by Suor** [comment]
Added ability to click tags to go to on demand validation directly from search results.

**Comment by dhimmel** [comment]
Great. The kappa displayed after an on-demand validation indicates whether your tags agreed with prior tags?

After doing a validation, it is a bit difficult to return to the original series for additional tagging.

**Comment by Suor** [comment]
Annotation kappa is kappa with original annotation. Best kappa is best
against any prior validation/annotation.

2015-08-01 3:33 GMT+07:00 Daniel Himmelstein <notifications@github.com>:
