### ISSUE TITLE
Download annotations

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#62]
Users need to download annotations.  We should add a 'Export' button to download annotations from the data.  For instance on this page users should be able to export annotations: http://stargeo.org/annotations/1/samples/

**Comment by ir4y** [comment]
@idrdex @Suor I added link to http://stargeo.org/annotations/
It looks more reasonable.

If we place this button to http://stargeo.org/annotations/1/samples/ page it could look like exporting sample annotations for only one current sample. However, the whole set of sample annotation will be exported.

**Comment by ir4y** [comment]
@idrdex
Now data is served as JSON. 
Should I add CSV format?

**Comment by zhilongjia** [comment]
It seems not a real-time result as I did not find the newest sample annotation by myself.
