### ISSUE TITLE
User freezes of annotations  

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#66]
We need to implement storing annotation sets for users. The easiest place for this on the front end is to extend the annotations interface: http://stargeo.org/annotations/. Users could add annotations to their freeze as needed from here. Analyses could be based on these freezes as analyses already save an automated data frame of annotations on S3. We also need the ability for users to publish these data #67.

**Comment by Suor** [comment]
Done. Everything starts from annotations page with "Make snapshot" button. Try it, reopen if any additional functionality needed or we can discuss it in skype.

**Comment by Suor** [comment]
**P.S.** Also added some special keywords to annotations search to ease making annotations. See at the bottom of the page or click ? next to search field.
