### ISSUE TITLE
Automatic tag updates when tag names change

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#7]
I would like to change tag names -- for consistency, clarity, or because of a convention switch.

@idrdex advised me against this practice for now because the tag value will remain unchanged. Can tag values for existing tags be updated when the tag name gets updated?

**Comment by Suor** [comment]
Added tag control section to edit tags. Tag names is updated in sample tags and validations correctly.

**Comment by dhimmel** [comment]
Also see https://github.com/idrdex/star-django/issues/8#issuecomment-128606009
