### ISSUE TITLE
Matching probes to refmrna algo incorrect

### ISSUE THREAD

**Issue by Suor** [idrdex/star-django#73]
Now we match all probes to all genes and take one with best score as result. There are two issues with that:
- best score can be however bad, meaning only small part or probe actually matches,
- if probe matches several genes, one is selected at random.

If we define condition better, like select "only unique gene containing the whole probe" I can reimplement it to be correct. 

Also, now blatting/parsing could be very slow - several hours for single platform - custom implementation can make it way faster and far less resource intensive.

**Comment by idrdex** [comment]
I think we want as liberal a match as possible. That it takes a long time is not an issue as it's only done once a new platform is encountered by the system. Probes can indeed map to several genes that may be in a large gene family like VAMPs or SYTs or a probe may match a common part of a protein that may be shared amon many genes. So I would just leave it. In any case if it is noise the meta analysis will weed out the crappy probe matches across multiple studies as such genes will be of low significance.

**Comment by Suor** [comment]
Maybe whatever I proposed is too strict, but now we are storing lots of trash random meaningless data. Probes use more than 60% of our db size now.

**Comment by Suor** [comment]
And we serving this via API.
