### ISSUE TITLE
Server 500 on analyses

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#74]
Seems like running new or re-running analyses crashes web server until the analysis is done.

**Comment by Suor** [comment]
Any particular analysis to run/rerun? I tried a few and everything works so far.

**Comment by idrdex** [comment]
I think it was a server load issue.  Connecting to postgres directly there this Error: Connection to PosgreSQL failed.  FATAL: sorry too many connections

**Comment by Suor** [comment]
I see those errors in logs and they happen on Sep 26/27 and most load is on Sep 28. Besides, there is no much load anyway and it shouldn't cause such errors. Django only creates one connection per process, which we have 4, celery creates few more. And we have 100 max connections in PostgreSQL.

This should be something else. Like runaway script, I added logging to refresh_data and fill_probes, which are suspicious to me. If it happens again, we will know the cause.

**Comment by Suor** [comment]
In fact I think I have found the issue. `refresh_data` was stopping, but not exiting on errors not releasing db connections. Fixed that.
