### ISSUE TITLE
Resolving a tag name-description conflict

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#8]
name: `PC_Control`
description: `Adjacent normal prostate tissue from PC patients`

The name implies that the tag should cover all samples from patients without prostate cancer. The description indicates that the tag is for PC cases but from normal tissue.

This also brings up the outstanding issue of how to deal to healthy tissue from diseased patients.

Suggestions?

**Comment by Suor** [comment]
Added a way to edit tags (names and description). It should be possible now to fix this.

**Comment by dhimmel** [comment]
Does this mean I can change tag names now or I should continue holding off?

**Comment by Suor** [comment]
Yes, you can edit tag names through tag control here - http://dev.stargeo.io/tags/. And corresponding annotations will be updated.

**Comment by dhimmel** [comment]
Nice interface for visualizing all the tags. Consider:

+ returning to the [tags page](http://dev.stargeo.io/tags/) after saving a tag edit
+ tag description appears on mouseover on the tags page

**Comment by Suor** [comment]
Added return to tags after edit and description in a hint. Also added a button to create tags.

**Comment by Suor** [comment]
Since this is content issue now, reassaigning it to @dhimmel.

**Comment by Suor** [comment]
One more thing. The way we query data to construct analysis dataframe right now makes tags with spaces unusable and yet we have some - http://dev.stargeo.io/tags/303/. I can change create/edit form in a way that it would not allow spaces in tag names.

**Comment by idrdex** [comment]
Yeah.  That’s a problem.  No spaces should be allowed in tag names.  How best to implement that?

dex*

**Comment by dhimmel** [comment]
> No spaces should be allowed in tag names.

Okay, I have started replacing spaces in tags with underscores.

Regarding the original name-description conflict, I renamed `PC_Control` to `PC_tissue_control`, so it better matches the description.

**Comment by Suor** [comment]
Tags with spaces as well as starting with a digit will be no longer allowed to prevent accidental errors. Now faulty tags still need to be updated manually.
